<?xml version="1.0"?>
<package format="3">
  <name>licam_fusion</name>
  <version>0.0.1</version>
  <description>DEOS Lidar-Camera Fusion Module</description>
  <maintainer email="ardaefe.yilmaz@deu.edu.tr">Arda Efe Yilmaz</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>message_filters</depend>
  <depend>vision_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_eigen</depend>
  <depend>libopencv-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>